const phillyVernacular = [
    'jawn',
    'hoagie',
    'shore',
    'fam',
    'jimmies',
    'ratchet',
    'wawa',
    'malarkey',
    'water ice',
    'cheesesteak',
    'whiz',
    'witout',
    'wit',
    'youse',
    'mac machine',
    'drawlin',
    'boul',
    'ard',
    'mummer',
    'yo',
    'phillies',
    'eagles',
    'flyers',
    'schuykill',
    'fishtown',
    'rocky',
    'hoagiefest',
    'saltwater taffy',
    'duck boats',
    'macroburst',
    'piney',
    'pork roll',
    'bon jovi',
    'jug handle',
    'AC',
    'philly',
    'phanatic',
    'turnpike',
    'no, yeah',
    'yeah, no',
    'liberty bell',
    'crick',
    'ya mean',
    'sup',
    'dawg',
    'aiite',
    'center city',
    'hotcake',
    'pavement',
    'scrapple',
    'square',
];

const getRandomWord = () => {
    return phillyVernacular[Math.floor(Math.random() * phillyVernacular.length)];
}